service: cache-test
 
package:
  individually: true
  
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage,'dev'}
  memorySize: 128
  lambdaHashingVersion: 20201221
  tracing: 
    lambda: true
  stackTags:
    PRODUCT: cache-test
    STAGE: ${self:provider.stage}
  deploymentBucket:
    name: serverless-deployment-102850798067
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource:
        - "*"

    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource: 
        - !GetAtt CacheTestTable.Arn

functions:
  APILambda:
    name: ${self:service}-api-lambda
    handler: index.lambda_handler
    environment:
      TABLE: !Ref CacheTestTable

resources:
  Resources:
    CacheTestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cache-test-table
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "N"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST